# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/marks/fabacademy/group/scanner/fruit3d/gui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(706, 409)
        MainWindow.setMaximumSize(QtCore.QSize(710, 410))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 681, 341))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.all_layout = QtWidgets.QVBoxLayout()
        self.all_layout.setContentsMargins(11, 11, 11, 11)
        self.all_layout.setSpacing(6)
        self.all_layout.setObjectName("all_layout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.sesion_line = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.sesion_line.setObjectName("sesion_line")
        self.horizontalLayout.addWidget(self.sesion_line)
        self.all_layout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.shots = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.shots.setMinimumSize(QtCore.QSize(153, 0))
        self.shots.setProperty("value", 18)
        self.shots.setObjectName("shots")
        self.horizontalLayout_2.addWidget(self.shots)
        self.all_layout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.levels = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.levels.setMinimumSize(QtCore.QSize(153, 0))
        self.levels.setProperty("value", 3)
        self.levels.setObjectName("levels")
        self.horizontalLayout_3.addWidget(self.levels)
        self.all_layout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.time = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.time.setMinimumSize(QtCore.QSize(140, 0))
        self.time.setProperty("value", 2)
        self.time.setObjectName("time")
        self.horizontalLayout_4.addWidget(self.time)
        self.all_layout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.treeView = QtWidgets.QTreeView(self.horizontalLayoutWidget)
        self.treeView.setObjectName("treeView")
        self.horizontalLayout_5.addWidget(self.treeView)
        self.all_layout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.all_layout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_51.setSpacing(6)
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_51.addWidget(self.label_5)
        self.ip_line = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.ip_line.setReadOnly(True)
        self.ip_line.setObjectName("ip_line")
        self.horizontalLayout_51.addWidget(self.ip_line)
        self.verticalLayout_2.addLayout(self.horizontalLayout_51)
        self.processingButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.processingButton.setObjectName("processingButton")
        self.verticalLayout_2.addWidget(self.processingButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.progress = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
        self.progress.setProperty("value", 0)
        self.progress.setObjectName("progress")
        self.verticalLayout_2.addWidget(self.progress)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.imageView = QtWidgets.QGraphicsView(self.horizontalLayoutWidget)
        self.imageView.setObjectName("imageView")
        self.verticalLayout_2.addWidget(self.imageView)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 706, 20))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fruit 3D Scanner"))
        self.label.setText(_translate("MainWindow", "Session:"))
        self.label_2.setText(_translate("MainWindow", "# shots:"))
        self.label_3.setText(_translate("MainWindow", "# levels:"))
        self.label_4.setText(_translate("MainWindow", "Time (min)"))
        self.label_5.setText(_translate("MainWindow", "IP"))
        self.processingButton.setText(_translate("MainWindow", "Processing"))

